networks:
  monitoring:
    driver: bridge

services:
  app:
    build: .
    container_name: "app-container"
    restart: always
    ports:
      - "8080:80"
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: "blackbox-exporter"
    restart: always
    ports:
      - "9115:9115"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:
