services:
  app:
    build: .
    container_name: "app-container"
    restart: always
    ports:
      - "8080:80"

  blackbox:
    image: prom/blackbox-exporter:latest
    restart: always
    ports:
      - "9115:9115"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
