- name: Initialize Docker Swarm (if not already)
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  register: swarm_init

- name: Get join token for workers (always)
  command: docker swarm join-token -q worker
  register: worker_token
  failed_when: worker_token.rc != 0

- name: Debug token generation
  debug:
    msg:
      - "Swarm init result: {{ swarm_init.changed }}"
      - "Worker token: {{ worker_token.stdout }}"
      - "Manager IP: {{ ansible_host }}"

- name: Verify token is not empty
  fail:
    msg: "Worker token is empty or undefined"
  when: worker_token.stdout is not defined or worker_token.stdout == ""

- name: Set facts globally using group_vars
  set_fact:
    swarm_worker_token: "{{ worker_token.stdout }}"
    swarm_manager_ip: "{{ ansible_host }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['all'] }}"

- name: Verify facts were set correctly
  debug:
    msg:
      - "Token set: {{ swarm_worker_token }}"
      - "Manager IP set: {{ swarm_manager_ip }}"
