- name: Initialize Docker Swarm (if not already)
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  register: swarm_init

- name: Get join token for workers (always)
  command: docker swarm join-token -q worker
  register: worker_token

- name: Debug token generation
  debug:
    msg:
      - "Swarm init result: {{ swarm_init.changed }}"
      - "Worker token: {{ worker_token.stdout }}"
      - "Manager IP: {{ ansible_host }}"

- name: Create swarm info file on manager
  copy:
    content: |
      swarm_worker_token: "{{ worker_token.stdout }}"
      swarm_manager_ip: "{{ ansible_host }}"
    dest: /tmp/swarm_info.yml
    mode: "0644"

- name: Set worker token fact for manager
  set_fact:
    swarm_worker_token: "{{ worker_token.stdout }}"
    swarm_manager_ip: "{{ ansible_host }}"

- name: Add to dummy host for sharing
  add_host:
    name: "swarm_info"
    swarm_worker_token: "{{ worker_token.stdout }}"
    swarm_manager_ip: "{{ ansible_host }}"
